webStore/Pages/App/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using webStore.Models;

namespace webStore.Pages.App
{
    public class CreateModel : PageModel
    {
        private readonly MST_AppStoreContext _db;

        private IHostingEnvironment _env;

        public CreateModel(MST_AppStoreContext db, IHostingEnvironment env)
        {
            _db = db;
            _env = env;
        }

        [BindProperty]
        public AppStore appstore { get; set; }

        [BindProperty]
        public IEnumerable<Category> Categories { get; set; }

        [BindProperty]
        public IFormFile Upload { get; set; }

        [BindProperty]
        public IEnumerable<IFormFile> UploadIpadFile { get; set; }

        [BindProperty]
        public IEnumerable<IFormFile> UploadMobileFile { get; set; }

        public SelectList CategorySelectList { get; set; }

        [BindProperty]
        public int SelectedCetegoryId { get; set; }

        public async Task OnGet()
        {
            var categoriesSelect = await _db.Category.Where(x => x.IsActive == true).ToListAsync();
            CategorySelectList = new SelectList(categoriesSelect, nameof(Category.Id), nameof(Category.Name));
        }

        public async Task<IActionResult> OnPost()
        {
            var getIntAppId = _db.AppStore.ToList().Last();
            var getIntFilePathId = _db.FilePath.ToList().Last();

            int AppId = getIntAppId.Id + 1;
            int PathId = getIntFilePathId.Id;

            AppStore Application = new AppStore();
            Application.Id = AppId;
            Application.Name = appstore.Name;
            Application.Title = appstore.Title;
            Application.CategoryId = SelectedCetegoryId;
            Application.Company = "MST";
            Application.Detail = appstore.Detail;
            Application.InformationCompatibility = appstore.InformationCompatibility;
            Application.InformationCopyright = appstore.InformationCopyright;
            Application.InformationLanguages = appstore.InformationLanguages;
            Application.InformationProvider = appstore.InformationProvider;

            //upload icon app
            var webRoot = _env.WebRootPath;
            var value = Guid.NewGuid().ToString();
            var directoryPath = Path.Combine(webRoot, "application\\" + value + "\\");
            if (!Directory.Exists(directoryPath))
            {
                Directory.CreateDirectory(directoryPath);
            }

            var directoryIconPath = Path.Combine(directoryPath, "Icon\\");
            if (!Directory.Exists(directoryIconPath))
            {
                Directory.CreateDirectory(directoryIconPath);
            }
            var Fullpath = System.IO.Path.Combine(directoryIconPath, Upload.FileName);
            using (var fileStream = new FileStream(Fullpath, FileMode.Create))
            {
                await Upload.CopyToAsync(fileStream);
                FilePath fp = new FilePath()
                {
                    Id = PathId + 1,
                    TypeFile = "icon",
                    OriginalFileName = Upload.FileName,
                    WebPath = "/application/" + value + "/Icon/" + Upload.FileName,
                    CreateDate = DateTime.Now,
                    CreateBy = HttpContext.Session.GetString("Username")
                };
                await _db.FilePath.AddAsync(fp);
                await _db.SaveChangesAsync();
                PathId += 1;
                Application.IconAppId = fp.Id;
            }
            //Upload screenshot ipad
            var directoryIpadPath = Path.Combine(directoryPath, "Ipad\\");
            if (!Directory.Exists(directoryIpadPath))
            {
                Directory.CreateDirectory(directoryIpadPath);
            }
            foreach (var item in UploadIpadFile)
            {
                var mapPath = System.IO.Path.Combine(directoryIpadPath, item.FileName);
                using (var fileStream = new FileStream(mapPath, FileMode.Create))
                {
                    await item.CopyToAsync(fileStream);
                    FilePath fp = new FilePath()
                    {
                        Id = PathId + 1,
                        TypeFile = "ipad",
                        OriginalFileName = item.FileName,
                        WebPath = "/application/" + value + "/Ipad/" + item.FileName,
                        CreateDate = DateTime.Now,
                        CreateBy = HttpContext.Session.GetString("Username")
                    };
                    await _db.FilePath.AddAsync(fp);
                    await _db.SaveChangesAsync();
                    ScreenshotFile sf = new ScreenshotFile()
                    {
                        AppId = Application.Id,
                        FileId = fp.Id
                    };
                    await _db.ScreenshotFile.AddAsync(sf);
                    await _db.SaveChangesAsync();
                    PathId += 1;
                }
            }
            //Upload screenshot mobile
            var directoryMobilePath = Path.Combine(directoryPath, "Mobile\\");
            if (!Directory.Exists(directoryMobilePath))
            {
                Directory.CreateDirectory(directoryMobilePath);
            }
            foreach (var item in UploadMobileFile)
            {
                var mapPath = System.IO.Path.Combine(directoryMobilePath, item.FileName);
                using (var fileStream = new FileStream(mapPath, FileMode.Create))
                {
                    await item.CopyToAsync(fileStream);
                    FilePath fp = new FilePath()
                    {
                        Id = PathId + 1,
                        TypeFile = "mobile",
                        OriginalFileName = item.FileName,
                        WebPath = "/application/" + value + "/Mobile/" + item.FileName,
                        CreateDate = DateTime.Now,
                        CreateBy = HttpContext.Session.GetString("Username")
                    };
                    await _db.FilePath.AddAsync(fp);
                    await _db.SaveChangesAsync();
                    ScreenshotFile sf = new ScreenshotFile()
                    {
                        AppId = Application.Id,
                        FileId = fp.Id
                    };
                    await _db.ScreenshotFile.AddAsync(sf);
                    await _db.SaveChangesAsync();
                    PathId += 1;
                }
            }
            Application.CreateDate = DateTime.Now;
            Application.CreateBy = HttpContext.Session.GetString("Username");
            await _db.AppStore.AddAsync(Application);
            await _db.SaveChangesAsync();
            return RedirectToPage("/App/MyApp", new { username = HttpContext.Session.GetString("Username") });
        }
    }
}

webStore/Pages/User/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using webStore.Models;

namespace webStore.Pages.User
{
    public class CreateModel : PageModel
    {
        private readonly MST_AppStoreContext _db;

        public CreateModel(MST_AppStoreContext db)
        {
            _db = db;
        }

        [BindProperty]
        public UserMaster user { get; set; }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                user.UserLevel = "user";
                user.CreateDate = DateTime.Now;
                user.IsActive = true;
                user.CreateBy = HttpContext.Session.GetString("Username");
                await _db.UserMaster.AddAsync(user);
                await _db.SaveChangesAsync();
                return RedirectToPage("/User/Index");
            }
            else
            {
                return Page();
            }
        }
    }
}

webStore/Pages/User/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using OfficeOpenXml;
using webStore.Models;

namespace webStore.Pages.User
{
    public class IndexModel : PageModel
    {
        private readonly MST_AppStoreContext _db;

        public IndexModel(MST_AppStoreContext db)
        {
            _db = db;
        }

        public IEnumerable<UserMaster> allUser;

        [BindProperty]
        public UserMaster userSelect { get; set; }

        public async Task OnGet()
        {
            string username = HttpContext.Session.GetString("Username");
            allUser = await _db.UserMaster.Where(x => x.Username != username).ToListAsync();
        }

        public async Task<IActionResult> OnPost()
        {
            var userEdit = await _db.UserMaster.FirstAsync(x => x.Username == userSelect.Username);
            if (userEdit != null)
            {
                userEdit.Username = userSelect.Username;
                userEdit.FirstName = userSelect.FirstName;
                userEdit.LastName = userSelect.LastName;
                userEdit.Email = userSelect.Email;
                userEdit.ModifyDate = DateTime.Now;
                userEdit.ModifyBy = HttpContext.Session.GetString("Username");
                await _db.SaveChangesAsync();
                return RedirectToPage("/User/Index");
            }
            return Page();
        }

        public async Task<IActionResult> OnPostDelete(string username)
        {
            var userDelete = await _db.UserMaster.FindAsync(username);
            if (userDelete == null)
            {
                return NotFound();
            }
            _db.UserMaster.Remove(userDelete);
            await _db.SaveChangesAsync();

            return RedirectToPage("/User/Index");
        }

        public async Task<IActionResult> OnPostExportExcel()
        {
            var list = await _db.UserMaster.ToListAsync();
            var stream = new MemoryStream();

            ExcelPackage.LicenseContext = LicenseContext.Commercial;
            string excelName = $"UserList-{DateTime.Now.ToString("yyyyMMddHHmmssfff")}.xlsx";
            using (var package = new ExcelPackage(stream))
            {
                var workSheet = package.Workbook.Worksheets.Add("Sheet1");
                workSheet.Cells.LoadFromCollection(list, true);
                package.Save();
                HttpContext.Response.Clear();
                HttpContext.Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                HttpContext.Response.Headers.Add("Content-Disposition", string.Format("attachment;filename={0}", excelName));
                HttpContext.Response.Body.WriteAsync(package.GetAsByteArray());
            }
            stream.Position = 0;
            //return File(stream, "application/octet-stream", excelName);
            return RedirectToPage("/User/Index");
        }
    }
}

webStore/Pages/User/Create.cshtml
@page
@model webStore.Pages.User.CreateModel
@{
}
<h1 class="text-info">Create Member</h1>
<hr />
<div class="container">
    <form method="post">
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <div class="form-group mb-2">
            <label asp-for="user.Username"></label>
            <input asp-for="user.Username" class="form-control" type="text" />
            <span asp-validation-for="user.Username" class="text-danger"></span>
        </div>
        <div class="form-group mb-2">
            <label asp-for="user.Password"></label>
            <input asp-for="user.Password" class="form-control" type="password" />
            <span asp-validation-for="user.Password" class="text-danger"></span>
        </div>
        <div class="form-group mb-2">
            <label asp-for="user.FirstName"></label>
            <input asp-for="user.FirstName" class="form-control" type="text" />
            <span asp-validation-for="user.FirstName" class="text-danger"></span>
        </div>
        <div class="form-group mb-2">
            <label asp-for="user.LastName"></label>
            <input asp-for="user.LastName" class="form-control" type="text" />
            <span asp-validation-for="user.LastName" class="text-danger"></span>
        </div>
        <div class="form-group mb-2">
            <label asp-for="user.Email"></label>
            <input asp-for="user.Email" class="form-control" type="text" />
            <span asp-validation-for="user.Email" class="text-danger"></span>
        </div>
        <input type="submit" value="Create" class="btn btn-block btn-success" />
    </form>
</div>
@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

webStore/Pages/User/Index.cshtml
@page
@model webStore.Pages.User.IndexModel
@{
}
<h1 class="text-info">Manage Member</h1>
<hr />
<div class="container">
    <div class="d-flex justify-content-between">
        <div>
            <a class="btn btn-md btn-success text-white mb-3" asp-page="/User/Create" asp-area=""><i class="fas fa-plus"></i>&nbsp; Add Member</a>
        </div>
        <div>
            <form method="post">
                <button class="btn btn-md btn-success text-white mb-3" asp-page-handler="ExportExcel"><i class="fas fa-file-excel"></i>&nbsp; ExportExcel</button>
            </form>
        </div>
    </div>
    <table id="tableAllUser" class="table table-striped table-bordered mt-3" style="width:100%">
        <thead>
            <tr>
                <th>Username</th>
                <th>Firstname</th>
                <th>Lastname</th>
                <th>Email</th>
                <th>CreateDate</th>
                <th>ModifyDate</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var user in Model.allUser)
            {
                <tr>
                    <td>@user.Username</td>
                    <td>@user.FirstName</td>
                    <td>@user.LastName</td>
                    <td>@user.Email</td>
                    <td>@user.CreateDate</td>
                    <td>@user.ModifyDate</td>
                    <td>
                        <form method="post">
                            <a class="btn btn-sm btn-warning text-white" data-toggle="modal" data-target="#@user.Username"><i class="fas fa-edit"></i></a>
                            <button asp-page-handler="Delete" asp-route-username="@user.Username" onclick="return confirm('Are you sure you want delete ?')" class="btn btn-sm btn-danger text-white"><i class="fas fa-trash"></i></button>
                        </form>
                        <form method="post">
                            <div id="@user.Username" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
                                <div class="modal-dialog modal-lg">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title">Edit @user.Username</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            @if (user.Username != null)
                                            {
                                                Model.userSelect = user;
                                            }
                                            <div class="container">
                                                <div class="form-group mb-2">
                                                    <label asp-for="userSelect.Username"></label>
                                                    <input asp-for="userSelect.Username" class="form-control" type="text" readonly />
                                                </div>
                                                <div class="form-group mb-2">
                                                    <label asp-for="userSelect.FirstName"></label>
                                                    <input asp-for="userSelect.FirstName" class="form-control" type="text" />
                                                </div>
                                                <div class="form-group mb-2">
                                                    <label asp-for="userSelect.LastName"></label>
                                                    <input asp-for="userSelect.LastName" class="form-control" type="text" />
                                                </div>
                                                <div class="form-group mb-2">
                                                    <label asp-for="userSelect.Email"></label>
                                                    <input asp-for="userSelect.Email" class="form-control" type="text" />
                                                </div>
                                                <input type="submit" value="Edit" class="btn btn-block btn-success" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>